#!/usr/bin/with-contenv bash
## Debug Mode
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ];  then
    set -x
fi

while [ ! -f /tmp/state/99-container-init ]
do
    sleep 1
done

## Start Zabbix Server
echo "[i] Starting Zabbix Server"
exec s6-setuidgid zabbix zabbix_server -f >/dev/null 2>&1;
