#!/usr/bin/with-contenv bash
while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

## Start Zabbix Server
echo ''
echo "[i] Starting Zabbix Server"
exec s6-setuidgid zabbix zabbix_server -f >/dev/null 2>&1;
