#!/usr/bin/with-contenv bash

SMTP_HOST=${SMTP_HOST:-"smtp.exmail.qq.com"}
SMTP_USER=${SMTP_USER:-"ivgz.notice@ivixq.com"}
SMTP_PASS=${SMTP_PASS:-"123456"}

INIT_FILE="`basename $0`-init"

if [ ! -f /tmp/state/$INIT_FILE ]; then
   sed -e "s/<SMTP_HOST>/$SMTP_HOST/g" -i /etc/zabbix/alertscripts/html_email.sh
   sed -e "s/<SMTP_USER>/$SMTP_USER/g" -i /etc/zabbix/alertscripts/html_email.sh
   sed -e "s/<SMTP_PASS>/$SMTP_PASS/g" -i /etc/zabbix/alertscripts/html_email.sh
   touch /tmp/state/$INIT_FILE
fi

