#!/usr/bin/with-contenv bash

WECHAT_CORPID=${WECHAT_CORPID:-""}
WECHAT_SECRET=${WECHAT_SECRET:-""}
WECHAT_APPID=${WECHAT_APPID:-""}
WECHAT_PARTYID=${WECHAT_PARTYID:-""}

INIT_FILE="`basename $0`-init"

if [ ! -f /tmp/state/$INIT_FILE ]; then
   sed -e "s/<WECHAT_CORPID>/$WECHAT_CORPID/g" -i /etc/zabbix/alertscripts/wechat.sh
   sed -e "s/<WECHAT_SECRET>/$WECHAT_SECRET/g" -i /etc/zabbix/alertscripts/wechat.sh
   sed -e "s/<WECHAT_APPID>/$WECHAT_APPID/g" -i /etc/zabbix/alertscripts/wechat.sh
   sed -e "s/<WECHAT_PARTYID>/$WECHAT_PARTYID/g" -i /etc/zabbix/alertscripts/wechat.sh
   touch /tmp/state/$INIT_FILE
fi

